[Server]
address = "0.0.0.0"
port = 19050
https = false
httpMaxConnections = 32
staticDir = "./public"
title = "nitter"
hostname = "localhost:19050"

[Cache]
# El bot chequea una vez por hora: no necesito cachear agresivo, pero tampoco pegarle de más
listMinutes = 240
rssMinutes = 10
redisHost = "nitter-redis"
redisPort = 6379
redisPassword = ""
redisConnections = 4
redisMaxConnections = 16

[Config]
# Generalo con: openssl rand -hex 32
hmacKey = "REEMPLAZAR"
base64Media = false
enableRSS = true
enableDebug = false
proxy = ""
proxyAuth = ""

[Preferences]
theme = "Nitter"
replaceTwitter = ""
replaceYouTube = ""
replaceReddit = ""
proxyVideos = true
hlsPlayback = false
infiniteScroll = false
